title: Alex Cristian
owner: Alex Cristian
email: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://acristian.eu" # the base hostname & protocol for your site, e.g. http://example.com
language: en
twitter_username: _AlexCristian
github_username: AlexCristian
disqus_username: disqus_RcWyiGlp5Z 
# Build settings
markdown: kramdown
theme: minima
encoding: UTF-8

permalink: /:year/:month/:day/:title/

gems:
  - jekyll-feed
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
excerpt_separator: <!--more-->
